# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{system_lock}
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.6") if s.respond_to? :required_rubygems_version=
  s.authors = ["rcarvalho"]
  s.date = %q{2012-10-16}
  s.description = %q{System Lock is a system-weide Ruby Critical Section that uses Memcached to lock}
  s.email = %q{i@rodneyc.me}
  
  s.files = Dir.glob("{rails,lib}/**/*") + %w(MIT-LICENSE README)
  
  s.homepage = %q{http://github.com/rcarvalho/system_lock}
  s.require_paths = ["lib"]
  s.summary = %q{Ruby system-wide lock using memcached}
end